version: '3.7'

services:
  blog:
    image: datasciencemagic:latest
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.datasciencemagic.rule=Host(`datasciencemagic.org`) || Host(`www.datasciencemagic.org`)"
      - "traefik.http.services.datasciencemagic.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.portainer.loadbalancer.server.port=80"
      - "traefik.http.routers.datasciencemagic.entrypoints=http"
      - "traefik.http.middlewares.datasciencemagic-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.datasciencemagic.middlewares=datasciencemagic-https-redirect"
      - "traefik.http.routers.datasciencemagic-secure.entrypoints=https"
      - "traefik.http.routers.datasciencemagic-secure.rule=Host(`datasciencemagic.org`) || Host(`www.datasciencemagic.org`)"
      - "traefik.http.routers.datasciencemagic-secure.tls=true"
      - "traefik.http.routers.datasciencemagic-secure.service=datasciencemagic"
    networks:
      - proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      # placement:
      #   constraints: [node.platform.os == linux]

networks:
  proxy:
    external: true
